### ISSUE TITLE
Getting  Jinja syntax error: unexpected '.'; line 20 while running the docker-node-demo via salt

### ISSUE THREAD

**Issue by ankush-grover-3pg** [jacksoncage/docker-node-demo#1]
Hi,

I am trying to run your docker-node-demo on Salt master to deploy few docker containers on a minion. I am getting the below error when I am trying to run this docker node-demo . I am running 2014.7.03(helium) version of Salt on Centos 7 64-bit and minions are both Ubuntu & Centos 6/7.

What could be the problem and how to fix this??

salt "ubuntu14.novalocal" state.sls containers.applications.node-demo
ubuntu14.novalocal:
##     Data failed to compile:

```
Rendering SLS "base:containers.applications.node-demo" failed: Jinja syntax error: unexpected '.'; line 20
```

---

[...]
{% for no in noofcontainers %}
{{ name }}-stop-if-old-{{ nr }}:
  module.run:
    - name: docker.stop
    - opts: '{{ containerid }}-{{ name }}-{{ nr }} [timeout=30]'
    - unless: docker inspect --format '{{ .Image }}' {{ containerid }}-{{ name }}-{{ nr }} | grep $(docker images --no-trunc | grep "https://registry.hub.docker.com/u/jacksoncage/{{ name }}" | grep "{{ tag }}" | awk '{ print $3 }')    <======================
    - require:
      - docker: {{ name }}-image

Replaced registry.bloglovin.com:5000 with url pointing to your docker image (https://registry.hub.docker.com/u/jacksoncage)

Do let me know if you need any more information.

Thanks & Regards
Ankush Grover

**Comment by jacksoncage** [comment]
@ankush-grover-3pg are you using the latest master code?

In latest master the '.' issue is fixed a raw jinja wrapper.

```
docker inspect --format '{% raw %}{{ .Image }}{% endraw %}' {{ containerid }}-{{ name }}-{{ nr }} | grep $(docker images --no-trunc | grep "{{ registryname }}/{{ name }}" | awk '{ print $3 }')
```

And registryname should be just `jacksoncage` to fetch down from Docker Hub.

**Comment by ankush-grover-3pg** [comment]
I tried with the latest master code. I will try once again. Just to share there is a small mistake in the node-demo.sls file on line 7 that is instead of  "‰" it should be "%" otherwise we get unicode errors while running.

Thanks & Regards

Ankush Grover

**Comment by jacksoncage** [comment]
Fixed character issue.

**Comment by ankush-grover-3pg** [comment]
With the latest code, the error coming up is 

Rendering SLS 'base:containers.applications.node-demo' failed: Jinja variable 'nr' is undefined

I am using helium version of salt. Can you provide the fix for the same..

Thanks & Regards

Ankush Grover

**Comment by jacksoncage** [comment]
@ankush-grover-3pg fix pushed, where an old variable laying around. Also updated range.

**Comment by ankush-grover-3pg** [comment]
Now another error cropping up

## Data failed to compile:

```
Rendering SLS 'base:containers.applications.node-demo' failed: Conflicting ID 'fetch_out_of_band'
```

**Comment by ankush-grover-3pg** [comment]
Any fix for "fetch_out_of_band' Conflicting ID??

Thanks & Regards
Ankush Grover

**Comment by jacksoncage** [comment]
That shouldn't even have been there from the beginning, now removed @ankush-grover-3pg
